### PR TITLE
[# 152988987] Create  User Registration form which allows uses to register

### PR DESCRIPTION
**Pull request by TheSteelGuy**
**What does this PR do?**

- Contains pure html codes which allows user to register

 **Description of the Task to be completed next:**
 **1)index.html containing**;

-   Login 
-  Create account links

**2) ManageAccount.html dashboard allowing users to:**

 

- Add events 
-  Modify events
-  Delete events
-  RSVP to an event
-  Retrieve people who RSVP for an event
-  Search for events
-  Filter events by location    
-  Filter events by category

### CODE REVIEW

**Comment by betsybeth** [comment]
The pull request description is not understandable.I believe you can do  better than that.Please check the conventions playbook sent by Nickii

**Comment by Mnickii** [comment]
Please implement the feedback I gave you.

**Comment by Mnickii** [comment]
Great. Now go ahead and merge, and create the githhub pages link

**Comment by betsybeth** [comment]
Good work.

**Pull request merged**
